[tool.poetry]
name = "trafikkmeldinger"
version = "0.1.0"
description = ""
authors = ["Martin Høy <marhoy@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"
requests-oauthlib = "^1.3.1"
pydantic = {extras = ["dotenv"], version = "^1.9.1"}
pandas = "^1.4.2"
fastapi = "^0.78.0"
uvicorn = "^0.17.6"
Jinja2 = "^3.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipykernel = "^6.13.0"
black = "^22.3.0"
flake8 = "^4.0.1"
mypy = "^0.960"
pydocstyle = "^6.1.1"
pre-commit = "^2.19.0"
types-requests = "^2.27.28"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
