[tool.poetry]
name = "trafikkmeldinger"
version = "0.1.0"
description = ""
authors = ["Martin Høy <marhoy@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"
pydantic = {extras = ["dotenv"], version = "^1.9.1"}
fastapi = "^0.78.0"
uvicorn = "^0.17.6"
Jinja2 = "^3.1.2"
requests-cache = "^0.9.4"
loguru = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1"
pytest-cov = "^3.0.0"
black = "^22.3.0"
flake8 = "^4.0.1"
mypy = "^0.960"
pydocstyle = "^6.1.1"
pre-commit = "^2.19.0"
types-requests = "^2.27.28"
ipykernel = "^6.13.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

# pytest configuration
[tool.pytest.ini_options]
addopts = "--cov-report term-missing:skip-covered --cov=trafikkmeldinger"
